services:
  postgres:
    image: postgres:18
    container_name: postgres_codearena
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: redis_codearena
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  db:
    driver: local
  redis_data:
    driver: local
